CREATE TABLE ECUACION_CUBICA (

    ID NUMBER GENERATED ALWAYS AS IDENTITY,

    A NUMBER(10,4),
    B NUMBER(10,4),
    C NUMBER(10,4),
    D NUMBER(10,4),

    RAIZ_REAL NUMBER(20,10),

    FECHA_CALCULO DATE DEFAULT SYSDATE,

    CONSTRAINT PK_ECUACION_CUBICA
    PRIMARY KEY(ID)
);

COMMIT;